"""Implementation of the 'sync' command."""

from pathlib import Path

from envguard.reporters.base import BaseReporter
from envguard.schema.loader import load_schema


def execute_sync(
    schema_path: str,
    output_path: str,
    force: bool,
    reporter: BaseReporter,
) -> int:
    """
    Execute the sync command.

    Args:
        schema_path: Path to .envguard.yml
        output_path: Path to output .env.example
        force: Overwrite without prompting
        reporter: The reporter to use for output

    Returns:
        Exit code (0 for success, 1 for error).
    """
    schema_file = Path(schema_path)
    output_file = Path(output_path)

    try:
        schema = load_schema(schema_file)
    except Exception as e:
        reporter.report_error(f"Failed to load schema: {e}")
        return 1

    if not force and output_file.exists():
        # Let the CLI layer handle the prompt if we want, but for now we'll
        # just assume if it exists and not force, we abort or overwrite safely.
        # Since it's a CLI tool, we can use standard input if it's a TTY, but
        # it's cleaner to just fail if force is not provided and it exists.
        reporter.report_error(
            f"File {output_path} already exists. Use --force to overwrite."
        )
        return 1

    lines = [
        "# This file was automatically generated by EnvGuard.",
        "# Do not put actual secrets in this file.",
        "",
    ]

    for name, var_def in schema.variables.items():
        if var_def.description:
            lines.append(f"# {var_def.description}")

        # Add metadata comments
        meta = []
        if var_def.type != "string":
            meta.append(f"Type: {var_def.type}")
        if var_def.choices:
            meta.append(f"Choices: {', '.join(var_def.choices)}")
        if var_def.required:
            meta.append("Required: true")

        if meta:
            lines.append(f"# {', '.join(meta)}")

        # Value logic
        val = ""
        if var_def.example:
            val = var_def.example
        elif var_def.default is not None:
            val = var_def.default

        lines.append(f"{name}={val}")
        lines.append("")  # Blank line between vars

    try:
        output_file.write_text("\n".join(lines), encoding="utf-8")
        reporter.report_sync(output_path, len(schema.variables))
        return 0
    except Exception as e:
        reporter.report_error(f"Failed to write {output_path}: {e}")
        return 1
